version: '3.8'
services:
  client:
    build: ./Client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

  server:
    build: ./Server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://xrazorx89:Ludp03HjDe3DTeXZ@cluster0.yu7q83g.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    restart: always
