name: Build and Deploy Server to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./Server
          file: ./Server/dockerfile
          push: true
          tags: imyuviii/fullstack-dep:latest

      - name: Test SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} echo "SSH connection successful"

      - name: Deploy to EC2 Instance
        if: success() # Only deploy if the SSH test is successful
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull imyuviii/fullstack-dep:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app -p 3005:3000 imyuviii/fullstack-dep:latest